language: node_js

node_js:
  - 14.x

# blacklist
branches:
  except:
    - master

#whitelist
  braches:
    only:
      - test_travis

before_install:
  - npm i

jobs:
  include:
    - stage: "run linting"
     script:  npm run lint

    - stage: "run tests"
      script: npm run coverage 
